name: paddle_det
channels:
  - defaults
dependencies:
  - python=3.9.25
  - pip
  - pip:
      - numpy==1.23.5
      - opencv-python==4.5.5.64
      - paddlepaddle-gpu==3.2.2
      - pillow==11.3.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.13.1
      - tqdm==4.67.1
      - numba==0.60.0
      - matplotlib==3.9.4
      - psutil==7.1.3
